version: '3'
services:
  app:
    image: apps
    build:
      context: .
      dockerfile: Dockerfile
    user: app
    networks:
      - app-network
  redis:
    image: redis:7.2
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-network
  postgres:
    image: postgres:16.3
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app-network:
    driver: bridge
