# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        database: ["postgresql://postgres:postgres@127.0.0.1/main", "mongodb://mongo:mongo@127.0.0.1/main?authSource=admin"]

    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up databases
        run: docker-compose up -d
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn run ${{ matrix.database }}
      - run: |
          yarn create-tables
          yarn start &
        env:
          DATABASE_URL: ${{ matrix.database }}
          NODE_ENV: production
          INIT_DATABASE_DATA: true
      - run: yarn workspace @app/_example01app test
      - run: yarn workspace @app/_example02app test
      - run: yarn workspace @app/_example03ant test
      - run: yarn workspace @app/_example04antpro test
      - run: yarn test
