# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TEST SERVER

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        database: ["postgresql://postgres:postgres@127.0.0.1/main", "mongodb://mongo:mongo@127.0.0.1/main?authSource=admin"]

    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up databases
        run: docker-compose up -d
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Start server for ${{ matrix.database }}
        run: |
          set -x
          [[ $DATABASE_URL == 'postgresql*' ]] && yarn workspace @app/_back02keystone migrate
          yarn test ./packages
          yarn dev ./apps/_back02keystone/multi-server &
          sleep 10
          yarn test ./apps/_back02keystone
        env:
          DATABASE_URL: ${{ matrix.database }}
          NODE_ENV: development
          DISABLE_LOGGING: true
