# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TEST APPS EXAMPLES

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --verbose --registry https://registry.npmjs.org
      - run: yarn run jest ./packages
      - run: yarn workspace @app/_example01app test
      - run: yarn workspace @app/_example02app test
      - run: yarn workspace @app/_example03ant test
      - run: yarn workspace @app/_example04antpro test
      - run: yarn workspace @app/_example05app test
      - run: yarn workspace @app/_pomodoro_app test
